<?php get_header(); ?>
<?php
$lead_post = null;
$sticky_posts = get_option('sticky_posts');

if (!empty($sticky_posts)) {
    $lead_query = new WP_Query(array(
        'post__in' => $sticky_posts,
        'posts_per_page' => 1,
        'ignore_sticky_posts' => 1,
    ));
    $lead_post = $lead_query->have_posts() ? $lead_query->posts[0] : null;
    wp_reset_postdata();
}

if (!$lead_post) {
    $lead_query = new WP_Query(array(
        'posts_per_page' => 1,
        'category_name' => 'lead-story',
        'ignore_sticky_posts' => 1,
    ));
    $lead_post = $lead_query->have_posts() ? $lead_query->posts[0] : null;
    wp_reset_postdata();
}

$lead_title = $lead_post ? get_the_title($lead_post) : __('The quiet art of building a family life that feels like your own.', 'the-family-lens');
$lead_excerpt = $lead_post ? get_the_excerpt($lead_post) : __('Thoughtful journalism, practical guidance and authentic storytelling for parents and carers who want clarity, curiosity and confidence without being told what to think.', 'the-family-lens');
$lead_url = $lead_post ? get_permalink($lead_post) : home_url('/start-here/');
?>
<section class="front-cover front-cover-stacked">
    <div class="cover-label"><span><?php esc_html_e('Issue 01', 'the-family-lens'); ?></span><span><?php esc_html_e('Modern family life, considered slowly', 'the-family-lens'); ?></span></div>
    <article class="lead-story">
        <p class="kicker"><?php esc_html_e('Lead story', 'the-family-lens'); ?></p>
        <h1><?php echo esc_html($lead_title); ?></h1>
        <p><?php echo esc_html($lead_excerpt); ?></p>
        <div class="actions"><a class="button" href="<?php echo esc_url($lead_url); ?>"><?php esc_html_e('Read the feature', 'the-family-lens'); ?></a><a href="<?php echo esc_url(home_url('/start-here/')); ?>" class="text-link"><?php esc_html_e('Start with the publication guide', 'the-family-lens'); ?></a></div>
    </article>
    <figure class="hero-image">
        <?php if ($lead_post && has_post_thumbnail($lead_post)) : ?>
            <?php echo get_the_post_thumbnail($lead_post, 'family-lens-hero'); ?>
        <?php else : ?>
            <img src="<?php echo family_lens_asset('family-lens-hero-photo.png'); ?>" alt="<?php esc_attr_e('A calm family moment connected to the lead story', 'the-family-lens'); ?>">
        <?php endif; ?>
        <?php if ($lead_post) : ?><figcaption><?php esc_html_e('Lead feature', 'the-family-lens'); ?></figcaption><?php endif; ?>
    </figure>
</section>
<section class="editor-letter"><div><p class="kicker"><?php esc_html_e('From the Editor', 'the-family-lens'); ?></p><h2><?php esc_html_e('A calm place to read, reflect and begin again.', 'the-family-lens'); ?></h2></div><div class="letter-copy"><p><?php esc_html_e('The Family Lens is not a feed to race through. It is a carefully curated publication for people who care about the texture of family life: the home, the learning, the walks, the worries, the discoveries and the small decisions that shape a week.', 'the-family-lens'); ?></p><p><?php esc_html_e('We will always choose clarity over noise, warmth over performance and useful questions over easy answers.', 'the-family-lens'); ?></p><img class="signature signature-image" src="<?php echo family_lens_asset('charlotte-signature-teal.png'); ?>" alt="Charlotte"></div></section>
<section class="start-here"><div class="brush-rule"></div><p class="kicker"><?php esc_html_e('Start Here', 'the-family-lens'); ?></p><h2><?php esc_html_e('Find the doorway that matches the season you are in.', 'the-family-lens'); ?></h2><div class="start-grid"><article><span>01</span><h3><?php esc_html_e('New to The Family Lens?', 'the-family-lens'); ?></h3><p><?php esc_html_e('Begin with the publication guide, our values and the six editorial pillars.', 'the-family-lens'); ?></p></article><article><span>02</span><h3><?php esc_html_e('Looking for practical help?', 'the-family-lens'); ?></h3><p><?php esc_html_e('Choose Live, Learn or Thrive for grounded ideas you can use gently.', 'the-family-lens'); ?></p></article><article><span>03</span><h3><?php esc_html_e('Need perspective?', 'the-family-lens'); ?></h3><p><?php esc_html_e('Explore, Connect and Discover offer stories, places and recommendations worth slowing down for.', 'the-family-lens'); ?></p></article></div></section>
<section class="edition"><div class="section-head"><p class="kicker"><?php esc_html_e('This edition', 'the-family-lens'); ?></p><h2><?php esc_html_e('Carefully chosen stories, not a chronological feed.', 'the-family-lens'); ?></h2></div><div class="edition-grid"><?php $cards = array('live' => 'Small rituals that help a home feel steady', 'learn' => 'How to keep curiosity alive without turning life into lessons', 'explore' => 'The local walk that makes a weekend feel wider'); foreach ($cards as $slug => $title) : ?><article class="feature-card <?php echo esc_attr($slug); ?>"><p><?php echo esc_html(ucfirst($slug)); ?></p><h3><?php echo esc_html__($title, 'the-family-lens'); ?></h3><span><?php esc_html_e('A carefully chosen story from this editorial pillar.', 'the-family-lens'); ?></span></article><?php endforeach; ?></div></section>
<section class="pillars" aria-labelledby="pillars-title"><div class="section-head compact"><p class="kicker"><?php esc_html_e('Editorial pillars', 'the-family-lens'); ?></p><h2 id="pillars-title"><?php esc_html_e('Six ways to see family life more clearly.', 'the-family-lens'); ?></h2></div><div class="pillar-grid"><?php $pillars = array(array('Live','Exploring the everyday realities, rhythms and relationships that shape modern family life.','live'),array('Learn','Championing curiosity, education and the idea that learning is a lifelong pursuit.','learn'),array('Explore','Celebrating the places, adventures and experiences that help families see the world differently.','explore'),array('Thrive','Supporting healthier, happier family lives through evidence, insight and practical ideas.','thrive'),array('Connect','Strengthening the conversations, communities and relationships that help families flourish.','connect'),array('Discover','Sharing thoughtful recommendations, trusted reviews and ideas that genuinely add value.','discover')); foreach ($pillars as $i => $pillar) : ?><article><span><?php echo esc_html(str_pad((string) ($i + 1), 2, '0', STR_PAD_LEFT)); ?></span><h3><?php echo esc_html($pillar[0]); ?></h3><p><?php echo esc_html($pillar[1]); ?></p><a href="<?php echo family_lens_category_url($pillar[2]); ?>"><?php echo esc_html(sprintf(__('Enter %s', 'the-family-lens'), $pillar[0])); ?></a></article><?php endforeach; ?></div></section>
<section class="meet-editor"><div class="meet-editor-copy"><p class="kicker"><?php esc_html_e('Meet the Editor', 'the-family-lens'); ?></p><h2><?php esc_html_e('Charlotte brings a clear, considered lens to modern family life.', 'the-family-lens'); ?></h2><p><?php esc_html_e('Charlotte writes and edits The Family Lens after two decades writing about modern family life. Her work combines thoughtful journalism with evidence, observation and lived experience.', 'the-family-lens'); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/editors-letter/')); ?>"><?php esc_html_e("Read Charlotte's latest editor's letter", 'the-family-lens'); ?> &rarr;</a></div><div class="meet-editor-signature" aria-hidden="true"><img src="<?php echo family_lens_asset('charlotte-signature-teal.png'); ?>" alt=""></div></section>
<section class="partnership"><p class="kicker"><?php esc_html_e('Partnerships', 'the-family-lens'); ?></p><h2><?php esc_html_e('Partner with The Family Lens', 'the-family-lens'); ?></h2><p class="partner-lede"><?php esc_html_e('Thoughtful journalism deserves thoughtful partnerships.', 'the-family-lens'); ?></p><p><?php esc_html_e('The Family Lens collaborates selectively with organisations, destinations, charities, researchers and brands whose work genuinely supports modern family life. Editorial integrity always comes first.', 'the-family-lens'); ?></p><p><?php esc_html_e('Editorial partnerships, destination features, product reviews, expert collaborations and long-term campaigns built around stories readers genuinely value.', 'the-family-lens'); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/partnerships/')); ?>"><?php esc_html_e('Explore partnership opportunities', 'the-family-lens'); ?> &rarr;</a></section>
<section class="editor-journey"><div class="editor-journey-head"><p class="kicker"><?php esc_html_e("The Editor's Journey", 'the-family-lens'); ?></p><h2><?php esc_html_e('Built on two decades of understanding family life', 'the-family-lens'); ?></h2></div><div class="editor-journey-copy"><p><?php esc_html_e('The Family Lens is the culmination of more than twenty years spent exploring what family life really looks like. That journey began by working directly with children and families, before moving into research, designing services and support for families, identifying gaps in the systems intended to help them, and writing extensively about the realities of modern family life.', 'the-family-lens'); ?></p><p><?php esc_html_e('Alongside that professional experience has been an equally important personal one: raising four children, each with their own personalities, strengths and challenges. Family life has never been an abstract subject. It has been lived every day.', 'the-family-lens'); ?></p><p><?php esc_html_e("Those experiences led to the creation of Mummy Fever, one of the UK's long-established independent family publications, where thousands of articles explored parenting, education, travel, health and the everyday questions families ask themselves.", 'the-family-lens'); ?></p><p><?php esc_html_e('The Family Lens is the next chapter. It builds on everything that came before while creating space for slower, deeper and more thoughtful journalism about modern family life.', 'the-family-lens'); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/publications/')); ?>"><?php esc_html_e("Explore Charlotte's publications", 'the-family-lens'); ?> &rarr;</a></div></section>
<section class="journal-newsletter journal-newsletter-stacked"><article class="journal-card"><p class="kicker"><?php esc_html_e('The Journal', 'the-family-lens'); ?></p><h2><?php esc_html_e('The thinking behind the publication.', 'the-family-lens'); ?></h2><p><?php esc_html_e("Editor's letters, editorial standards, behind-the-scenes reflections and notes on how The Family Lens is built.", 'the-family-lens'); ?></p><a class="button gold" href="<?php echo esc_url(home_url('/the-journal/')); ?>"><?php esc_html_e('Visit The Journal', 'the-family-lens'); ?></a></article><article class="newsletter-card"><p class="kicker"><?php esc_html_e('Newsletter', 'the-family-lens'); ?></p><h2><?php esc_html_e('A quieter inbox starts here.', 'the-family-lens'); ?></h2><p><?php esc_html_e('A considered note with thoughtful stories, seasonal ideas and recommendations that have earned their place.', 'the-family-lens'); ?></p><form><input type="email" aria-label="<?php esc_attr_e('Email address', 'the-family-lens'); ?>" placeholder="<?php esc_attr_e('Email address', 'the-family-lens'); ?>"><button class="button" type="submit"><?php esc_html_e('Join', 'the-family-lens'); ?></button></form></article></section>
<section class="editorial-principles"><div class="principles-head"><p class="kicker"><?php esc_html_e('Our Editorial Principles', 'the-family-lens'); ?></p><h2><?php esc_html_e('We believe...', 'the-family-lens'); ?></h2></div><div class="principles-grid"><?php $principles = array('Family life deserves nuance.','Evidence matters.','Curiosity beats certainty.','Ordinary moments deserve attention.',"Readers' time should never be wasted.",'Integrity always comes before influence.'); foreach ($principles as $principle) : ?><article><span aria-hidden="true">&#10003;</span><p><?php echo esc_html($principle); ?></p></article><?php endforeach; ?></div></section>
<?php get_footer(); ?>
